version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: crud_db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Juanferr1098!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=CrudProduct;User Id=sa;Password=Juanferr1098!;TrustServerCertificate=True;

volumes:
  sql_data:
